
services:
  web:
    build: .
    command: gunicorn SBH.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=False
    volumes:
      - .:/code  # Mount code for development if needed
      - ./db.sqlite3:/app/db.sqlite3
